version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_APP_BLOCKCHAIN_RPC_URL=http://blockchain:8545
    working_dir: /app
    command: ["npm", "run", "dev"]
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules
            


  smart-contract:
    build:
      context: ./smart-contract
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    volumes:
      - ./smart-contract:/app
      - /app/node_modules
    working_dir: /app
    command: ["npx", "hardhat", "node"]

